version: '3.9'


services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mvc
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: mvc_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
